### ISSUE TITLE
Problem downloading package from pip

### ISSUE THREAD

**Issue by matteusgui** [naomilago/pt_lemmatizer#1]
The package has an issue, especially when downloaded from pip.

When downloaded from pip the package has the issue that the folder *data/* is not downloaded with it, making the package unusable directly from pip install.

This can be easily solved adding the lines:
include_package_data=True,
package_data = {'':['data/*.txt']},

to the setup.py file as shown at: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files

I submitted a pull request alongside with this issue.

Thanks by now and by the awesome project.

**Comment by naomilago** [comment]
Hi, @matteusgui!

Thanks for pointing out this issue. As my first PyPI package, I have some homework to do.
I've accepted your pull request and the changes should be shipped soon. I appreciate your help 😄
